spring:
  application:
    name: azit-server
server:
  servlet:
    encoding:
      force-response: true

#mail:
#  smtp:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    auth: true
#    starttls:
#      enable: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope:
#              - email
#              - profile
#          github:
#            client-id: ${GITHUB_CLIENT}
#            client-secret: ${GITHUB_SECRET}
#            scope:
#              - user
#              - user:email

jwt:
  secret-key: ${JWT_SECRET_KEY:DOFHUEWJKF8971938576439NGBJCBGVYUGFTYSFRC56TUH8NUK6JNYO9UGV8WE678REFKUG3K6HG9283} # dummy
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com # dummy
redis:
  port: 6379
  host: localhost
  password: ${REDIS_PASSWORD:redisPassTest0101} # dummy