spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

logging:
  level:
    root: INFO

# S3 Cloud
aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY_SERVER}       # AWS IAM AccessKey
    secretKey: ${AWS_SECRET_ACCESS_KEY_SERVER}   # AWS IAM SecretKey
  s3:
    bucket: azit-server-s3
  region: ap-northeast-2
