spring:
  application:
    name: azit-server
  jpa:
    defer-datasource-initialization: true  # 초기 데이터값 입력
  sql:
    init:
      encoding: UTF-8  # 한글 깨짐 해결
      mode: always
  servlet:
    multipart: # multipart 설정
      max-file-size: 8MB
      max-request-size: 8MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:449408918885-n2g7lrbc7sc43qhd6njnumavonk94g4o.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET} # 재설정 가능
            scope:
              - email
              - profile
server:
  servlet:
    encoding:
      force-response: true

jwt:
  secret-key: ${JWT_SECRET_KEY:DOFHUEWJKF8971938576439NGBJCBGVYUGFTYSFRC56TUH8NUK6JNYO9UGV8WE678REFKUG3K6HG9283} # dummy
  access-token-expiration-minutes: 10 # FE 요청으로 임시 변경
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: ${ADMIN_EMAIL:Anonymous} # dummy
  host: smtp.naver.com
  port: 465
  username: ${EMAIL_USERNAME:Anonymous}
  password: ${EMAIL_PASSWORD:dummy}
  properties:
    debug: true
    mail:
      smtp:
        auth: true
        ssl:
          enable: true
          trust: smtp.naver.com
        starttls:
          enable: true

redis:
  port: 6379
  host: localhost
