# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:  # dev branch로 pull request시에 테스트 코드의 정상 작동 유무를 확인합니다.
    branches: [ "dev" ]
    paths: [ "azit-back/**" ]  # azit-back 폴더의 변경사항만 적용

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./azit-back

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # gradlew에 실행 권한 부여
      - name: Add permission
        run: chmod +x ./gradlew

      # Backend code test
      - name: Server unit test
        run: ./gradlew test
